/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.page;

/**
 *
 * @author Hp
 */
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class AddDiagnosisInformation extends javax.swing.JFrame {
    public int flag = 0,count = 0;
    Connection conn;
    ResultSet rs,rs1,rs3;
    PreparedStatement pst,pst1,pst3;

    /**
     * Creates new form AddDiagnosisInformation
     */
    public AddDiagnosisInformation() {
        initComponents();
        conn = javaconnect.ConnecrDb();
        jTextField1.setVisible(false);
        //jComboBox1.setVisible(false);
        //jLabel7.setVisible(false);
        //jTextField6.setEditable(false);
        //jTextField7.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Patient Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("G:\\Project\\picture\\HMS ICON\\search.png")); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 570, 68));

        jTextField1.setText("    Patient Id doesn't  exit");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 180, 40));

        jLabel3.setText("Symptoms :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 235, 68, 40));

        jLabel4.setText("  Diagnosis:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 320, 60, 32));

        jLabel5.setText("Medicines :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 62, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 235, 370, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 370, 40));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 370, 40));

        jButton3.setIcon(new javax.swing.ImageIcon("G:\\Project\\picture\\HMS ICON\\Close.png")); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 130, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 40));

        jButton4.setIcon(new javax.swing.ImageIcon("G:\\Project\\picture\\HMS ICON\\save-icon--1.png")); // NOI18N
        jButton4.setText("save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\Project\\picture\\28643506.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home x = new home();
        x.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
/*String sql = “SELECT * FROM table WHERE something = ? “;
ps = con.preparedStatement(sql);
ps.setString(1, “whereValue”);
rs = ps.executeQuery();

jTableObject.setModel(DbUtils.resultSetToTableModel(rs));*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a1 = jTextField5.getText();
        String sql = "select *from addnewpatientrecord where PatientId = '"+a1+"'";
        
        //String PatientId = jTextField5.getText();
        try{
           // Connection conn = ConnectionProvider.getConn();
            //Statement st = conn.createStatement();
            //rs = = st.executeQuery("select *from AddDiagnosisInformation where PatientId='"+PatientId+"'" );
            pst = conn.prepareStatement(sql);
            pst1 = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            rs1 = pst1.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            if(rs.next())
            {
               jTextField1.setVisible(false);
               jTextField5.setEditable(false);
                 //jComboBox1.setVisible(true);
                // jLabel7.setVisible(false);
                 flag = 1;
                rs.close();
                pst.close();
            }
            else
            {
                
                
                  jTextField1.setVisible(true);
                //jTextField5.setEditable(false);
                //jComboBox1.setVisible(false);
                //rs.close();
                //pst.close();
                //flag = 1;
                
            }
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null,"connection error");            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(flag == 1)
        {
            
            /*String val_1 = jTextField5.getText();
            String val_2  = jTextField2.getText();
            String val_3 = jTextField3.getText();
            String val_4 = jTextField4.getText();
            String WardRequired;
           String Typeofward;
            if(jCheckBox1.isSelected())
            {
                WardRequired = "YES";
                Typeofward   = (String)jComboBox1.getSelectedItem();
                
            }
            else
            {
                WardRequired = "";
                Typeofward = "";
                
            }*/
            try{
           String sql ="insert into AddDiagnosisInformation   (PatientId, Symptoms,Diagnosis,Medicines) values (?,?,?,?)";
           //String sql ="Insert into  AddDiagnosisInformation ('"+val_1+"','"+val_2+"','"+val_3+"','"+val_4+"')";//'"+WardRequired+"','"+Typeofward+"')";
            pst= conn.prepareStatement(sql);
             pst.setString(1,jTextField5.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
                       
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "saved");
            
            setVisible(false);
            AddDiagnosisInformation x = new AddDiagnosisInformation();
            x.setVisible(true);
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Patient Id field is empty.");
        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiagnosisInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiagnosisInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
